Repository dandeduck/Voyager, pull requests merged in 2020-08, with the labels that each got.

#1 Implement navigation
  app/src/main/java/com/navapp/navigation/destination/Destination.java
  app/src/main/java/com/navapp/navigation/destination/data/Address.java
  app/src/main/java/com/navapp/navigation/destination/data/PhoneNumber.java
  app/src/main/java/com/navapp/navigation/destination/data/Rate.java
  app/src/main/java/com/navapp/navigation/route/Route.java
  app/src/main/java/com/navapp/navigation/route/RouteHandler.java
  app/src/main/java/com/navapp/navigation/route/RouteOptimizer.java
Labels: enhancement

#4 Added upsert: insert or update, to default store.
  app/src/androidTest/java/com/navapp/data/DefaultStoreModelTest.java
  app/src/main/java/com/navapp/data/DefaultStoreDao.java
  app/src/main/java/com/navapp/data/DefaultStoreModel.java
Labels: enhancement

#5 removed RouteHandler
  app/src/main/java/com/navapp/navigation/route/RouteHandler.java
  app/src/main/java/com/navapp/navigation/route/RouteOptimizer.java
Labels: enhancement

#7 Create LICENSE.txt
  LICENSE.md
  README.md
Labels: enhancement, help wanted

#9 Adding support for the anti 996 movement
  LICENSE.md
  README.md
Labels: enhancement

#8 Integrated Google's APIs and some small stuff
  app/build.gradle
  app/src/main/java/com/navapp/MainActivity.java
  app/src/main/java/com/navapp/navigation/destination/Destination.java
  app/src/main/java/com/navapp/navigation/destination/PlaceAutocomplete.java
  app/src/main/java/com/navapp/navigation/destination/data/Address.java
  app/src/main/java/com/navapp/navigation/destination/data/Location.java
  app/src/main/java/com/navapp/navigation/destination/data/PhoneNumber.java
  app/src/main/java/com/navapp/navigation/destination/data/Rate.java
  app/src/main/java/com/navapp/navigation/route/OptimizingRouteFactory.java
  app/src/main/java/com/navapp/navigation/route/Route.java
  app/src/main/java/com/navapp/navigation/route/RouteFactory.java
  app/src/main/java/com/navapp/navigation/route/RouteOptimizer.java
  app/src/main/java/com/navapp/navigation/route/RoutePlanner.java
  app/src/test/java/com/nvapp/navigation/destination/data/PhoneNumberTest.java
  app/src/test/java/com/nvapp/navigation/route/OptimizingRouteFactoryTest.java
  app/src/test/java/com/nvapp/navigation/route/RouteTest.java
  build.gradle
Labels: enhancement

#11 added travis thingy
  .travis.yml
  README.md
Labels: CI, enhancement
